

CREATE TABLE drivers (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(15) NOT NULL,
    cnh VARCHAR(9) NOT NULL UNIQUE,
    placa VARCHAR(7) NOT NULL UNIQUE,
    status VARCHAR(20) DEFAULT 'DISP' NOT NULL CHECK (status IN ('DISP', 'OCC', 'N/A'))
);
